package Scanner;

enum TokenType {
  // Single-character tokens.
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_SQUARE_BRACKET, RIGHT_SQUARE_BRACKET,
  EQUAL, COMMA, PLUS, STAR, SLASH, SEMICOLON,

  // One or two character tokens.
  GREATER, GREATER_EQUAL,
  MINUS, MINUS_GRATER,
  LESS, LESS_EQUAL, LESS_GRATER,
  COLON, COLON_COLON, COLON_EQUAL,

  DOT, DOT_DOT,

  // Literals.
  IDENTIFIER, STRING, NUMBER,

  // Keywords.
  TRUE, FALSE, NULL, // Values
  AND, OR, XOR, NOT, IMPLIES, // Booleans
  MODEL, CLASS, ATTRIBUTES, OPERATIONS, // Classes
  STATE_MACHINES, INITIAL, FINAL, // State machines
  ASSOCIATION, ASSOCIATION_CLASS, AGGREGATION, COMPOSITION, // Associations
  SELF, BEGIN, END, INIT, DERIVED, CONTEXT, INV, PRE, AT_SYMBOL_PRE, POST, BETWEEN, IF, THEN, ELSE, END_IF, // OCL
  NEW, DESTROY, INSERT, DELETE, INTO, FROM, DECLARE, FOR, IN, DO, // SOIL

  // Operations
  MOD, DIV, ABS, MAX, MIN, ROUND, FLOOR, // Numbers
  CONCAT, TO_LOWER, TO_UPPER, SUBSTRING, // Strings
  OCL_IS_NEW, OCL_IS_UNDEFINED, OCL_AS_TYPE, OCL_IS_TYPE_OF, OCL_IS_KIND_OF, OCL_IS_IN_STATE, ALL_INSTANCES, // OclAny
  HAS_RETURNED, RESULT, IS_SIGNAL_SENT, IS_OPERATION_CALL, // OclMessage
  COUNT, EXCLUDES, EXCLUDES_ALL, INCLUDES, INCLUDES_ALL, IS_EMPTY, NOT_EMPTY, SIZE, SUM, // Standard
  ANY, COLLECT, COLLECT_NESTED, EXISTS, FOR_ALL, IS_UNIQUE, ITERATE, ONE, REJECT, SELECT, SORTED_BY, // Iteration

  // End of the file
  EOF
}
